# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
# SPDX-License-Identifier: Apache-2.0

FROM gcr.io/etcd-development/etcd:%%ETCD_VERSION%% as source
FROM alpine:3.18.2

WORKDIR /

RUN apk add --update bash curl wget openssl

COPY --from=source /usr/local/bin/etcd /usr/local/bin
COPY --from=source /usr/local/bin/etcdctl /usr/local/bin

ENTRYPOINT ["/usr/local/bin/etcd"]
