#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
# SPDX-License-Identifier: Apache-2.0

set -e

# For the build step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

cd "${SOURCE_PATH}"

VERSION_FILE="${SOURCE_PATH}/VERSION"
DOCKERFILE="${SOURCE_PATH}/Dockerfile"
DOCKERFILE_TEMPLATE="${SOURCE_PATH}/Dockerfile.template"

###############################################################################

VERSION=`/cc/utils/cli.py githubutil greatest_release_version --github-repository-url https://github.com/etcd-io/etcd --anonymous`
export VERSION="v$VERSION"
echo "FETCHED ETCD VERSION: $VERSION"

cat << EOF > ${VERSION_FILE}
$VERSION
EOF

sed -e "s/ETCD_VERSION/$VERSION/g" $DOCKERFILE_TEMPLATE > $DOCKERFILE

cat $DOCKERFILE

echo
echo "EFFECTIVE_VERSION: $EFFECTIVE_VERSION"

echo
echo "git diff:"
git --no-pager diff

echo
if git diff-index --quiet HEAD; [ $? -eq 0 ] ; then
  echo "No version change"
else
  echo "Publishing version change"
  git commit -am "Updated etcd image version to $VERSION
\`\`\`feature operator
Update etcd from $EFFECTIVE_VERSION to $VERSION. :warning: This will cause a restart of the etcd.
\`\`\`
  " || git --no-pager log -1
fi
