#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
# SPDX-License-Identifier: Apache-2.0

set -e

# For the build step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.

echo $SOURCE_PATH
pwd
ls -al

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

echo "new"
echo "BUILD_PATH: $(readlink -f "${BUILD_PATH}")"
export BUILD_PATH="$(readlink -f "${BUILD_PATH}")"

cd "${SOURCE_PATH}"

VERSION_FILE="${SOURCE_PATH}/VERSION"
DOCKERFILE="${SOURCE_PATH}/build/Dockerfile"

###############################################################################

echo "EFFECTIVE_VERSION: $EFFECTIVE_VERSION"

cd build
pwd
ls -al
cat Dockerfile

cd "${SOURCE_PATH}"

sed -i "s/ETCD_VERSION/$EFFECTIVE_VERSION/g" $DOCKERFILE

cat $DOCKERFILE

cp $DOCKERFILE $BUILD_PATH/Dockerfile
