#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
# SPDX-License-Identifier: Apache-2.0

set -e

# For the build step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.

echo $SOURCE_PATH
pwd
ls -al

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

if [[ -z "${BUILD_PATH}" ]]; then
  export BUILD_PATH="${SOURCE_PATH}/build"
else
  export BUILD_PATH="$(readlink -f "${BUILD_PATH}")/build"
fi

cd "${SOURCE_PATH}"

VERSION_FILE="${SOURCE_PATH}/VERSION"
DOCKERFILE="${SOURCE_PATH}/build/Dockerfile"

###############################################################################

echo "EFFECTIVE_VERSION: $EFFECTIVE_VERSION"

cd $SOURCE_PATH
pwd
ls -al
cd ..
ls -al

cd $SOURCE_PATH

sed -i "s/ETCD_VERSION/$EFFECTIVE_VERSION/g" $DOCKERFILE

